# Generated by Django 4.2.7 on 2023-11-07 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicfarewell', '0003_tag_publicfarewell_questions_publicfarewell_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfarewell',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
