# Generated by Django 4.2.7 on 2023-11-08 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0005_alter_publicfarewell_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='publicfarewell',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='publicfarewell',
            name='tag',
        ),
        migrations.AlterField(
            model_name='publicfarewell',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='publicfarewell',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='publicfarewell.questions'),
        ),
    ]
