# Generated by Django 4.2.7 on 2023-11-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0006_questions_remove_publicfarewell_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfarewell',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
