# Generated by Django 4.2.7 on 2023-11-08 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0007_alter_publicfarewell_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfarewell',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicfarewell.questions'),
        ),
    ]
