# Generated by Django 4.2.7 on 2023-11-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0008_alter_publicfarewell_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfarewell',
            name='hidden',
            field=models.TextField(default='False'),
        ),
    ]
