# Generated by Django 4.2.7 on 2023-11-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0009_publicfarewell_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfarewell',
            name='owner',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='publicfarewell',
            name='hidden',
            field=models.BooleanField(default='False'),
        ),
    ]
