# Generated by Django 4.2.7 on 2023-11-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0011_alter_publicfarewell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfarewell',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicfarewell',
            name='name',
            field=models.CharField(default='질문기본값', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
