# Generated by Django 4.2.7 on 2023-11-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0011_alter_publicfarewell_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfarewell',
            name='name',
            field=models.CharField(blank=True, default='기본값', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
