# Generated by Django 4.2.7 on 2023-11-11 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0012_alter_publicfarewell_id_alter_publicfarewell_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfarewell',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publicfarewell.questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
    ]
