# Generated by Django 4.2.7 on 2023-11-07 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myfarewell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='available_after',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
