# Generated by Django 4.2.7 on 2023-11-07 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_keyword_userprofile'),
        ('myfarewell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='available_after',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
