# Generated by Django 4.2.7 on 2023-11-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicfarewell', '0008_alter_publicfarewell_question'),
        ('myfarewell', '0002_remove_question_available_after_answer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_rate', models.IntegerField(default='0%')),
                ('answer_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfarewell.answer')),
                ('public_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_public_content', to='publicfarewell.publicfarewell')),
                ('public_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_public_image', to='publicfarewell.publicfarewell')),
                ('public_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_public_name', to='publicfarewell.publicfarewell')),
                ('public_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_public_questions', to='publicfarewell.publicfarewell')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfarewell.question')),
            ],
        ),
    ]
