# Generated by Django 4.2.7 on 2023-11-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfarewell', '0003_alter_question_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
